#----------- ID HEADER -------------------------------------
#  Author(s):	Andrew Boisvert, Kyle Scidmore
#  Email(s):    abois526@mtroyal.ca, kscid125@mtroyal.cas
#  File Name:   MAKEFILE
#
#  Program Purpose(s):
#    To help determine what parts of the program need to be
#    recompiled, and to aid in the process of doing so.
#-----------------------------------------------------------

#--------- Variable declarations ---------------------------
# Targets and objects
TARGET=kash
OBJECTS=kash.o stringlib.o 

# CC stuff
CC=gcc
CFLAGS=-g


#--------- Building, Linking, Cleaning ---------------------
# Building the target
all: clean $(TARGET)

# Linking target executable from object files
$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET)

# Cleaning up the old object files and executable
clean:
	$(RM) *.o $(TARGET)


#--------- Creating Object Files --------------------------- 
kash.o: kash.c
	$(CC) $(CFLAGS) -c kash.c 

stringlib.o: stringlib.c stringlib.h 
	$(CC) $(CFLAGS) -c stringlib.c 

# The empty line above this comment must remain to avoid errors